<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.0.0.55</Version>
    <PackageProjectUrl>https://github.com/Neycourt5/AutoUnderCut</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Neycourt5/AutoUnderCut.git</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SmartUndercutBot.Core\SmartUndercutBot.Core.csproj" />
  </ItemGroup>
</Project>
